"""empty message

Revision ID: 0fac58c5a72e
Revises: 4e755338fdbe
Create Date: 2019-02-22 21:34:34.613907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fac58c5a72e'
down_revision = '4e755338fdbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('correta', sa.Integer(), nullable=True),
    sa.Column('ativado', sa.Boolean(), nullable=True),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questoes')
    # ### end Alembic commands ###
