"""Relashionship de questão com matéria

Revision ID: 16d4cb20f2a7
Revises: b0061c1ff86d
Create Date: 2019-03-31 01:30:33.714498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d4cb20f2a7'
down_revision = 'b0061c1ff86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questoes', sa.Column('materia_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questoes', 'materias', ['materia_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questoes', type_='foreignkey')
    op.drop_column('questoes', 'materia_id')
    # ### end Alembic commands ###
