"""Melhorias na parte de professor

Revision ID: 303f0e8e531b
Revises: 402e7a839abc
Create Date: 2019-02-01 17:52:14.253630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303f0e8e531b'
down_revision = '402e7a839abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professores', sa.Column('unidade_academica_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professores', 'unidade_academica_id')
    # ### end Alembic commands ###
