"""Um pequeno contra tempo nas migrações

Revision ID: 402e7a839abc
Revises: 
Create Date: 2019-02-01 00:02:14.604455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402e7a839abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=True),
    sa.Column('data_deletado', sa.DateTime(), nullable=True),
    sa.Column('id_deletor', sa.Integer(), nullable=True),
    sa.Column('motivo_delete', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=True),
    sa.Column('data_deletado', sa.DateTime(), nullable=True),
    sa.Column('id_deletor', sa.Integer(), nullable=True),
    sa.Column('motivo_delete', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('hhash', sa.String(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('curso', sa.String(length=64), nullable=True),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=True),
    sa.Column('data_deletado', sa.DateTime(), nullable=True),
    sa.Column('id_deletor', sa.Integer(), nullable=True),
    sa.Column('motivo_delete', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=120), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('semestre', sa.String(length=80), nullable=True),
    sa.Column('tipo_conteudo', sa.String(length=120), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_submissao', sa.DateTime(), nullable=True),
    sa.Column('data_deletado', sa.DateTime(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=True),
    sa.Column('id_deletor', sa.Integer(), nullable=True),
    sa.Column('motivo_delete', sa.String(length=600), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arquivos')
    op.drop_table('usuarios')
    op.drop_table('professores')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
