"""Arquivo salvando sua extensao como png jpg, etcetara

Revision ID: 45fd61eb5d94
Revises: 303f0e8e531b
Create Date: 2019-02-08 01:36:53.173638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fd61eb5d94'
down_revision = '303f0e8e531b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arquivos', sa.Column('extensao', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arquivos', 'extensao')
    # ### end Alembic commands ###
