"""Campo de avatar em usuário

Revision ID: 4e755338fdbe
Revises: 984e06d96c2e
Create Date: 2019-02-22 13:29:53.499183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e755338fdbe'
down_revision = '984e06d96c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('avatar', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'avatar')
    # ### end Alembic commands ###
