"""modificações para facilitar a nota de um arquivo

Revision ID: 984e06d96c2e
Revises: ea87a02aec38
Create Date: 2019-02-21 00:54:43.657306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984e06d96c2e'
down_revision = 'ea87a02aec38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arquivos', sa.Column('nota', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arquivos', 'nota')
    # ### end Alembic commands ###
