"""empty message

Revision ID: ea87a02aec38
Revises: 98ff41b255e7
Create Date: 2019-02-19 21:08:45.004154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea87a02aec38'
down_revision = '98ff41b255e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao_arquivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('data_nota', sa.DateTime(), nullable=True),
    sa.Column('arquivo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('avalicao_arquivo')
    op.add_column('arquivos', sa.Column('ativado', sa.Boolean(), nullable=True))
    op.add_column('disciplinas', sa.Column('id_criador', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplinas', 'id_criador')
    op.drop_column('arquivos', 'ativado')
    op.create_table('avalicao_arquivo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nota', sa.INTEGER(), nullable=False),
    sa.Column('data_nota', sa.DATETIME(), nullable=True),
    sa.Column('arquivo_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('avaliacao_arquivo')
    # ### end Alembic commands ###
