"""is eligible para ativado

Revision ID: ef996314b129
Revises: 45fd61eb5d94
Create Date: 2019-02-18 14:48:01.618183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef996314b129'
down_revision = '45fd61eb5d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('arquivos', sa.Column('ativado', sa.Boolean(), nullable=True))
    with op.batch_alter_table("arquivos") as batch_op:
        batch_op.drop_column('is_eligible')
    with op.batch_alter_table("disciplinas") as batch_op:
        batch_op.add_column(sa.Column('ativado', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_eligible')
    with op.batch_alter_table("professores") as batch_op:
        batch_op.add_column(sa.Column('ativado', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_eligible')
    with op.batch_alter_table("usuarios") as batch_op:
        batch_op.add_column(sa.Column('ativado', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_eligible')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_eligible', sa.BOOLEAN(), nullable=True))
    op.drop_column('usuarios', 'ativado')
    op.add_column('professores', sa.Column('is_eligible', sa.BOOLEAN(), nullable=True))
    op.drop_column('professores', 'ativado')
    op.add_column('disciplinas', sa.Column('is_eligible', sa.BOOLEAN(), nullable=True))
    op.drop_column('disciplinas', 'ativado')
    op.add_column('arquivos', sa.Column('is_eligible', sa.BOOLEAN(), nullable=True))
    op.drop_column('arquivos', 'ativado')
    # ### end Alembic commands ###
